### PR TITLE
Regression test for importing from io

### PR DESCRIPTION
**Pull request by aij**
Works with sbt-ensime 1.12.15 (or no ensime plugin), but with
sbt-ensime 2.0.0 and 2.0.1 this fails with

```
/build.sbt:1: error: object gatling is not a member of package sbt.io
import io.gatling.sbt.GatlingKeys._
```

A workaround is to use an absolute import, so that io doesn't resolve
to `sbt.io`.

Ideally, sbt-ensime shouldn't import sbt.io into the scope of the
build file, as that should be a per-project decision, whereas
the choice to use ensime should be per-user.

### CODE REVIEW

**Comment by fommil** [comment]
this is a standard problem with things that start `io.`. You can do `import _root_.io....`

see https://contributors.scala-lang.org/t/proposed-syntax-for--root-/1035

I don't know how or why ensime is importing an `io` and I cannot confirm that it is `sbt.io` Might be an sbt bug. // @dwijnand ?

**Comment by dwijnand** [comment]
> sbt-ensime shouldn't import sbt.io into the scope of the build file

It's sbt that imports `sbt._` into the build file, and this is a consequence.. This has nothing to do with sbt-ensime. This reminds me of https://github.com/sbt/sbt-multi-jvm/issues/22.

**Comment by aij** [comment]
@dwijnand Could you explain why it works fine without sbt-ensime, as well as with sbt-ensime 1.12.15, but breaks with sbt-ensime 2.0.0?

I'm having a hard time imagining how the version of sbt-ensime could have nothing to do with sbt-ensime.

**Comment by dwijnand** [comment]
Could you give me a minimised reproduction? I'm not an (sbt-)ensime user.

**Comment by aij** [comment]
@dwijnand Is this PR not minimal enough? I suppose I could make it a couple lines smaller...

IRL, the `addSbtPlugin("org.ensime" % "sbt-ensime" % ...)` line would be in `~/.sbt/0.13/plugins/plugins.sbt` rather than in `project/build.sbt`, and with a fixed version number rather than using getProperty.

If you want to test manually, with Paul Phillips' sbt runner script, you can:

```
aij@altos:~/git/ensime-sbt$ cd src/sbt-test-0.13/sbt-ensime/import-io
aij@altos:~/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io$ sbt -sbt-dir ~/tmp/no/sbt/globals -Dplugin.version=1.12.15 test
Getting org.scala-sbt sbt 0.13.15  (this may take some time)...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        49 artifacts copied, 0 already retrieved (17577kB/39ms)
Getting Scala 2.10.6 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        5 artifacts copied, 0 already retrieved (24494kB/21ms)
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/project
[info] Updating {file:/home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/project/}import-io-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.gatling/gatling-sbt/scala_2.10/sbt_0.13/2.2.2/jars/gatling-sbt.jar ...
[info]  [SUCCESSFUL ] io.gatling#gatling-sbt;2.2.2!gatling-sbt.jar (1121ms)
[info] Done updating.
[info] Set current project to root (in build file:/home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/)
[info] Updating {file:/home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/}root...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 0 s, completed Sep 28, 2017 12:15:35 PM
```
Now with 2.0.1:

```
aij@altos:~/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io$ sbt -sbt-dir ~/tmp/no/sbt/globals -Dplugin.version=2.0.1 test
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/project
[info] Updating {file:/home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/project/}import-io-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
/home/aij/git/ensime-sbt/src/sbt-test-0.13/sbt-ensime/import-io/build.sbt:1: error: object gatling is not a member of package sbt.io
import io.gatling.sbt.GatlingKeys._
          ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by fommil** [comment]
(there is a minimised reproduction in the PR btw)

**Comment by dwijnand** [comment]
My bad, hadn't realised this was a PR.
